// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLMonitorAPI.Data;

namespace SQLMonitorAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200102154015_UpdatedColumns")]
    partial class UpdatedColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SQLMonitorAPI.Models.SQLInstance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IsAlwaysOn")
                        .HasColumnType("int");

                    b.Property<int>("IsClustered")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfDatabases")
                        .HasColumnType("int");

                    b.Property<string>("OSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalServerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SQLCollation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SQLCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SQLEdition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SQLVersion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SQLInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
